// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:46361936475:web:08c4860078938cd751f57e',
    messagingSenderId: '46361936475',
    projectId: 'joystick-dc535',
    authDomain: 'joystick-dc535.firebaseapp.com',
    databaseURL:
        'https://joystick-dc535-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'joystick-dc535.firebasestorage.app',
    measurementId: 'G-Q4JRVBQTGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:46361936475:android:7d3aa68ce954307c51f57e',
    messagingSenderId: '46361936475',
    projectId: 'joystick-dc535',
    databaseURL:
        'https://joystick-dc535-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'joystick-dc535.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:46361936475:web:fadbc81863034c4851f57e',
    messagingSenderId: '46361936475',
    projectId: 'joystick-dc535',
    authDomain: 'joystick-dc535.firebaseapp.com',
    databaseURL:
        'https://joystick-dc535-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'joystick-dc535.firebasestorage.app',
    measurementId: 'G-KPQTDJNNJ5',
  );
}
